# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.log_dir}/tensorboard/${dataset}/${domain}"
  name: null
  log_graph: False
  default_hp_metric: True
  prefix: ""
  version: "${version}"
