# @package _global_

defaults:
  - _self_
  - data: null
  - model: vfae.yaml
  - callbacks: default.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "fair_representation"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.log_dir}/${dataset}/${domain}/${version}/checkpoints/best.ckpt
